name: Rust

permissions:
  contents: write
  
on:
  push:
    tags:
      - 'v*.*.*' # Trigger on version

env:
  CARGO_TERM_COLOR: always

jobs:
  build_linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - name: Build
      run: cargo build --release
    - name: Cargo Check All Features
      run: cargo check --all-features
    - uses: actions/upload-artifact@v4
      with:
        name: krokett_editor_linux_${{ github.ref_name }}
        path: target/release/krokett_editor_native
    - run: mv target/release/krokett_editor_native target/release/krokett_editor_linux_${{ github.ref_name }}
    - name: Release bin to GitHub
      uses: softprops/action-gh-release@v2
      with:
        files: target/release/krokett_editor_linux_${{ github.ref_name }}

  build_windows:
    runs-on: windows-latest
    if: false # Windows build is currently disabled
    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - name: Builds
      run: cargo build --release
    - name: Cargo Check All Features
      run: cargo check --all-features
    - uses: actions/upload-artifact@v4
      with:
        name: krokett_editor_windows_${{ github.ref_name }}.exe
        path: target\release\krokett_editor_native.exe
    - run: mv target/release/krokett_editor_native target/release/krokett_editor_windows_${{ github.ref_name }}.exe
    - name: Release bin to GitHub
      uses: softprops/action-gh-release@v2
      with:
        files: target\release\krokett_editor_windows_${{ github.ref_name }}.exe

  wasm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - name: Install trunk
      run: wget -qO- https://github.com/thedodd/trunk/releases/latest/download/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -xzf-
    - name: Build Web
      run: env -C krokett_editor_web trunk build

  android:
    runs-on: ubuntu-latest
    if: false # Android build is currently disabled
    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - name: Setup Java JDK
      uses: actions/setup-java@v4.5.0
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Setup Android SDK
      uses: android-actions/setup-android@v3
    - name: Install Cargo NDK
      run: cargo install cargo-ndk
    - name: Build APK
      working-directory: ./krokett_editor_android
      run: make apk
    - uses: actions/upload-artifact@v4
      with:
        name: krokett_editor-android.apk
        path: krokett_editor_android/java/app/build/outputs/apk/release/app-release-unsigned.apk

  tests-lints:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - name: Tests
      run: cargo test --verbose
    - name: Formatting
      run:  cargo fmt --all --check
    - name: Clippy
      run:  cargo clippy --all-features -- -D warnings 
    - name: Documentation
      run:  cargo doc --no-deps
